language: node_js
node_js:
- '10'

branches:
  only:
  - master

cache:
  directories:
  - node_modules

script:
  - yarn build
  - NOW_DEPLOY_ID=$( now --no-clipboard --token=$NOW_TOKEN )
  - now alias --token=$NOW_TOKEN
  - now rm zukrec --safe -y --token=$NOW_TOKEN
