language: node_js
node_js:
- '10'

branches:
  only:
  - master

cache:
  directories:
  - node_modules

script:
  - yarn build

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
