openapi: '3.0.1'
info:
  title: ZukVnc
  description: 'ZukRec的RESTFul接口文档<br>'
  version: '1.2'
servers: 
  - url: https://rec.zukdoor.cloud/api/v1
tags:
  - name: task
    description: 进行中任务相关接口
  - name: stopped-task
    description: 已停止任务相关接口
  - name: instance
    description: 实例相关接口
  - name: user
    description: 用户相关接口
components:
  schemas:
    UserStatistics:
      type: object
      properties:
        taskNum:
          type: number
          description: 任务数量
        recordNum:
          type: number
          description: 录像数量
        totalTaskTimes:
          type: number
          description: 任务总时长，单位为毫秒
    TaskInfo:
      type: object
      properties:
        taskArn:
          type: string
        ec2InstanceId:
          type: string
        ip:
          type: string
        createdTime:
          type: string
    RecordFile:
      type: object
      properties:
        taskId:
          type: number
        recordName:
          type: string
        createdTime:
          type: string
        size:
          type: number
    VncTask:
      type: object
      properties:
        id:
          type: number
          format: int64
        userId:
          type: string
        startTime:
          type: number
          description: unix时间戳
        stopTime:
          type: number
          description: unix时间戳
        recordingName:
          type: string
          description: 正在录像的文件名
        rtmpUrls:
          type: array
          description: 正在推流的地址集合
          items:
            type: object
            description: 推流信息
            properties:
              id:
                type: number
              url:
                type: string
        recordFiles:
          type: array
          description: 已录制的录像文件名集合
          items:
            $ref: '#/components/schemas/RecordFile'
        ended:
          type: boolean
    VncUserInfoUnWindTasks:
      type: object
      properties:
        id:
          type: number
          format: int64
        userId:
          type: string
        task:
          $ref: '#/components/schemas/PendingVncTask'
    ListAllStopedTaskResponse:
      type: object
      properties:
        totalCount:
          type: number
          format: int32
        page:
          type: number
          format: int32
        data:
          $ref: '#/components/schemas/TaskInfo'
    PendingVncTask:
      type: object
      properties:
        display:
          type: number
          format: int64
        userId:
          type: string
        url:
          type: string
        callback:
          type: string
        createdTime:
          type: number
          description: unix时间戳
    RunningVncTask:
      type: object
      properties:
        display:
          type: number
          format: int64
        userId:
          type: string
        url:
          type: string
        callback:
          type: string
        createdTime:
          type: number
          description: unix时间戳
paths:
  /tasks:
    post:
      tags:
        - task
      summary: '创建新任务'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - url
              properties:
                url:
                  type: string
                  description: 页面链接，任务对应的页面url
                callback:
                  type: string
                  description:  回调地址
                region:
                  type: string
                  description:  任务运行的区域，当前仅支持us-east-1和cn-north-1
              example: 
                url: 'https://www.zhihu.com/'
                callback: 'http://18.234.175.38:10003/api/v1/test/callback'
                region: 'cn-north-1'
      responses:
        '202':
          description: 服务器已收到创建请求
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PendingVncTask'
        '401':
          description: 用户未登录
    get:
      tags:
        - task
      summary: '列出所有任务'
      parameters:
        - name: pageSize
          in: query
          description: 每一页展示的任务数量，默认为20
          schema: 
            type: number
        - name: pageNum
          description: 页数，从0开始，默认为0
          in: query
          schema: 
            type: number
        - name: userId
          in: query
          schema: 
            type: string
        - name: stopped
          in: query
          schema: 
            type: boolean
        - name: startedTime
          in: query
          schema: 
            type: number
        - name: stoppedTime
          in: query
          schema: 
            type: number
      responses:
        '200':
          description: 操作成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/VncTask'
                  totalCount:
                    type: number
        '401':
          description: 用户未登录
        '403':
          description: 用户无权限
  /tasks/{display}:
    patch:
      tags:
        - task
      summary: '修改任务参数'
      parameters:
        - name: display
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                audioOffsetMillisecond:
                  type: number
                  description: 音频偏移时间
                autoOffset:
                  type: boolean
                  description:  是否自动调整音频偏移
                rp:
                  type: number
                  description:  调整屏幕分辨率
      responses:
        '200':
          description: 操作成功
        '401':
          description: 用户未登录
        '403':
          description: 用户无权限
        '404':
          description: 任务不存在
    delete:
      tags:
        - task
      summary: '停止任务'
      parameters:
        - name: display
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 成功停止
        '401':
          description: 用户未登录
        '403':
          description: 用户无权限
        '404':
          description: 任务不存在
  /tasks/{display}/records:
    post:
      tags:
        - task
      summary: '开始录制'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - recordName
              properties:
                recordName:
                  type: string
                  description: 录像名称，同一任务中的录像名称不能重复
                format:
                  type: string
                  description: 录像格式，默认为mkv
                onlyAudio:
                  type: boolean
                  description: 是否只录制音频，默认为否
      parameters:
        - name: display
          in: path
          required: true
          schema:
            type: string
      responses:
        '202':
          description: 收到开始录制请求
        '401':
          description: 用户未登录
        '403':
          description: 用户无权限
        '404':
          description: 任务不存在
        '409':
          description: 该任务正在录制中或录像名重复
    delete:
      tags:
        - task
      summary: '停止录制'
      parameters:
        - name: display
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 成功停止
        '401':
          description: 用户未登录
        '403':
          description: 用户无权限
        '404':
          description: 任务不存在
  /tasks/{display}/rtmps:
    post:
      tags:
        - task
      summary: '开始推流'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - rtmpUrl
              properties:
                rtmpUrl:
                  type: string
                  description: 推流地址
      parameters:
        - name: display
          in: path
          required: true
          schema:
            type: string
      responses:
        '202':
          description: 收到开始推流请求
          content:
            application/json:
              schema:
                type: object
                properties:
                  rtmpId:
                    type: integer
        '401':
          description: 用户未登录
        '403':
          description: 用户无权限
        '404':
          description: 任务不存在
        '409':
          description: 推流地址重复
  /tasks/{display}/rtmps/{rtmpId}:
    delete:
      tags:
        - task
      summary: '停止推流'
      parameters:
        - name: display
          in: path
          required: true
          schema:
            type: string
        - name: rtmpId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: 停止推流成功
        '401':
          description: 用户未登录
        '403':
          description: 用户无权限
        '404':
          description: 任务不存在
  /tasks/{display}/clicks:
    post:
      tags:
        - task
      summary: '模拟鼠标点击'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - x
              - y
              properties:
                x:
                  type: number
                  description: 横坐标
                y:
                  type: number
                  description: 纵坐标
      parameters:
        - name: display
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: 模拟点击成功
        '401':
          description: 用户未登录
        '403':
          description: 用户无权限
        '404':
          description: 任务不存在
  /stopped-tasks:
    get:
      tags:
        - stopped-task
      summary: '获取已结束任务信息'
      parameters:
        - name: pageSize
          in: query
          required: false
          description: '每一页的任务数量'
          schema:
            type: number
        - name: pageNum
          in: query
          required: false
          description: '第几页，从0开始计数'
          schema:
            type: number
      responses:
        '200':
          description: 任务信息
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ''
  /stopped-tasks/{display}/records/{recordName}/urls:
    post:
      tags:
        - stopped-task
      summary: '生成录像地址'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - expireTime
              properties:
                expireTime:
                  type: number
                  description: 有效期时间，单位为秒
      parameters:
        - name: display
          in: path
          required: true
          schema:
            type: string
        - name: recordName
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: 录像url
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
        '401':
          description: 用户未登录
        '403':
          description: 用户无权限
        '404':
          description: 任务不存在
  /instances:
    get:
      tags:
        - instance
      summary: '获取所有运行中实例'
      responses:
        '200':
          description: 所有实例
          content:
            application/json:
              schema:
                type: object
                properties:
                  region:
                    type: string
                    description: 所在区域
                  instance:
                    $ref: '#/components/schemas/TaskInfo'
        '401':
          description: 用户未登录
        '403':
          description: 用户无权限
  /users/{userId}/statistics:
    get:
      tags:
        - user
      summary: '获取用户统计信息'
      parameters:
        - name: userId
          in: path
          required: true
          schema: 
            type: string
        - name: start
          in: query
          schema: 
            type: number
            description: 起始时间，代码为毫秒
        - name: end
          in: query
          schema: 
            type: number
            description: 结束时间，代码为毫秒
      responses:
        '200':
          description: 操作成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/VncTask'
                  totalCount:
                    type: number
        '401':
          description: 用户未登录
        '403':
          description: 用户无权限