openapi: '3.0.1'
info:
  title: ZukVnc
  description: 'ZukRec的RESTFul接口文档<br>说明: 调用方式及参数在相关接口中有详细描述！<br>'
  version: '1.0'
servers: 
  - url: rec.zukdoor.cloud/zukvnc
tags:
  - name: record
    description: 录制相关接口
  - name: rtmp-controller
    description: 推流相关接口
paths:
  /api/v1/record/start:
    post:
      tags:
        - record
      summary: '开始录制，返回值为任务的id，如果想对同一面板进行推流，可在推流接口传入此id。回调通过POST方法请求，参数包括display, message。其中message有三种，record_success，record_failed，record_stopped'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - display
              - url
              - recordName
              properties:
                display:
                  type: integer
                  format: int64
                  description: 面板id（不指定特定面板时，需传入-1）
                url:
                  type: string
                  description: 页面链接，准备录制的页面url
                recordName:
                  type: string
                  description: 视频描述
                callback:
                  type: string
                  description:  回调地址，参数包括message：录制状态.分为开启录制成功，开启录制失败，录制结束
      responses:
        '201':
          description: 任务已创建
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/v1/record/stop:
    post:
      tags:
        - record
      summary: '停止录制，返回本次录制的相关信息，具体见返回描述.回调通过POST方法请求，参数包括display, message, data。其中message有两种，video_upload_success，video_upload_failed，data为s3的url'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - display
              - url
              - recordName
              properties:
                display:
                  type: integer
                  format: int64
                  description: 面板id
                callback:
                  type: string
                  description:  回调地址，参数包括message：录制状态.分为上传成功，上传失败；data：录像文件在s3上的url
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/v1/record/info:
    get:
      tags:
        - record
      summary: 获取录制信息，若出现错误通过此接口发现
      parameters:
        - name: display
          in: query
          description: 任务id
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/v1/rtmp/start:
    post:
      tags:
        - rtmp-controller
      summary: '推流，返回值为display，如果想对同一面板进行录制，可在录制接口传入此display.回调通过POST方法请求，参数包括display, message, data.其中message有三种，push_success，push_failed，push_stopped，data为rtmlUrl'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - display
              - url
              - recordName
              properties:
                display:
                  type: integer
                  format: int64
                  description: 面板id（不指定特定面板时，需传入-1）
                url:
                  type: string
                  description: 页面链接，准备录制的页面url
                rtmpUrl:
                  type: string
                  description: 推流地址，同一面板可推向多个地址
                callback:
                  type: string
                  description:  回调地址，参数包括message：录制状态.分为开启录制成功，开启录制失败，录制结束
      responses:
        '201':
          description: 任务已创建
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/v1/rtmp/stop:
    post:
      tags:
        - rtmp-controller
      summary: 停止推流
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - display
              - url
              - recordName
              properties:
                display:
                  type: integer
                  format: int64
                  description: 面板id
                rtmpUrl:
                  type: string
                  description: 停止推流的地址
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
