openapi: '3.0.1'
info:
  title: ZukVnc
  description: 'ZukRec的RESTFul接口文档<br>'
  version: '1.2'
servers: 
  - url: https://rec.zukdoor.cloud/api/v1
tags:
  - name: task
    description: 进行中任务相关接口
  - name: stopped-task
    description: 已停止任务相关接口
components:
  schemas:
    PendingVncTask:
      type: object
      properties:
        display:
          type: number
          format: int64
        userId:
          type: string
        url:
          type: string
        callback:
          type: string
        createdTime:
          type: number
          description: unix时间戳
paths:
  /tasks:
    post:
      tags:
        - task
      summary: '创建新任务'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - url
              properties:
                url:
                  type: string
                  description: 页面链接，任务对应的页面url
                callback:
                  type: string
                  description:  回调地址
                region:
                  type: string
                  description:  任务运行的区域，当前仅支持us-east-1和cn-north-1
      responses:
        '202':
          description: 服务器已收到创建请求
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PendingVncTask'
        '401':
          description: 用户未登录
  /tasks/{display}:
    patch:
      tags:
        - task
      summary: '修改任务参数'
      parameters:
        - name: display
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                audioOffsetMillisecond:
                  type: number
                  description: 音频偏移时间
                autoOffset:
                  type: boolean
                  description:  是否自动调整音频偏移
                rp:
                  type: number
                  description:  调整屏幕分辨率
      responses:
        '200':
          description: 操作成功
        '401':
          description: 用户未登录
        '403':
          description: 用户无权限
        '404':
          description: 任务不存在
    delete:
      tags:
        - task
      summary: '停止任务'
      parameters:
        - name: display
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 成功停止
        '401':
          description: 用户未登录
        '403':
          description: 用户无权限
        '404':
          description: 任务不存在
  /tasks/{display}/records:
    post:
      tags:
        - task
      summary: '开始录制'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - recordName
              properties:
                recordName:
                  type: string
                  description: 录像名称，同一任务中的录像名称不能重复
                format:
                  type: string
                  description: 录像格式，默认为mkv
                onlyAudio:
                  type: boolean
                  description: 是否只录制音频，默认为否
      parameters:
        - name: display
          in: path
          required: true
          schema:
            type: string
      responses:
        '202':
          description: 收到开始录制请求
        '401':
          description: 用户未登录
        '403':
          description: 用户无权限
        '404':
          description: 任务不存在
        '409':
          description: 该任务正在录制中或录像名重复
    delete:
      tags:
        - task
      summary: '停止录制'
      parameters:
        - name: display
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 成功停止
        '401':
          description: 用户未登录
        '403':
          description: 用户无权限
        '404':
          description: 任务不存在
  /tasks/{display}/rtmps:
    post:
      tags:
        - task
      summary: '开始推流'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - rtmpUrl
              properties:
                rtmpUrl:
                  type: string
                  description: 推流地址
      parameters:
        - name: display
          in: path
          required: true
          schema:
            type: string
      responses:
        '202':
          description: 收到开始推流请求
          content:
            application/json:
              schema:
                type: object
                properties:
                  rtmpId:
                    type: integer
        '401':
          description: 用户未登录
        '403':
          description: 用户无权限
        '404':
          description: 任务不存在
        '409':
          description: 推流地址重复
  /tasks/{display}/rtmps/{rtmpId}:
    delete:
      tags:
        - task
      summary: '停止推流'
      parameters:
        - name: display
          in: path
          required: true
          schema:
            type: string
        - name: rtmpId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: 停止推流成功
        '401':
          description: 用户未登录
        '403':
          description: 用户无权限
        '404':
          description: 任务不存在
  /tasks/{display}/clicks:
    post:
      tags:
        - task
      summary: '模拟鼠标点击'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - x
              - y
              properties:
                x:
                  type: number
                  description: 横坐标
                y:
                  type: number
                  description: 纵坐标
      parameters:
        - name: display
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: 模拟点击成功
        '401':
          description: 用户未登录
        '403':
          description: 用户无权限
        '404':
          description: 任务不存在
  /stopped-tasks/{display}/records/{recordName}/urls:
    post:
      tags:
        - stopped-task
      summary: '生成录像地址'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - expireTime
              properties:
                expireTime:
                  type: number
                  description: 有效期时间，单位为秒
      parameters:
        - name: display
          in: path
          required: true
          schema:
            type: string
        - name: recordName
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: 录像url
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
        '401':
          description: 用户未登录
        '403':
          description: 用户无权限
        '404':
          description: 任务不存在