openapi: '3.0.1'
info:
  title: ZukVnc
  description: 'ZukRec的RESTFul接口文档<br>说明: 调用方式及参数在相关接口中有详细描述！<br>'
  version: '1.1'
servers: 
  - url: https://rec.zukdoor.cloud/api/v1
tags:
  - name: task
    description: 任务相关接口
components:
  schemas:
    PendingVncTask:
      type: object
      properties:
        display:
          type: number
          format: int64
        userId:
          type: string
        url:
          type: string
        callback:
          type: string
        createdTime:
          type: number
          description: unix时间戳
paths:
  /tasks:
    post:
      tags:
        - task
      summary: '创建新任务。该接口为异步接口，任务成功开始后发送回调事件task-started'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - url
              properties:
                url:
                  type: string
                  description: 页面链接，任务对应的页面url
                callback:
                  type: string
                  description:  回调地址
      responses:
        '202':
          description: 服务器已收到创建请求
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PendingVncTask'
        '401':
          description: Unauthorized
  /tasks/{display}:
    delete:
      tags:
        - task
      summary: '停止任务。该接口为同步接口'
      parameters:
        - name: display
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 成功停止
        '401':
          description: Unauthorized